### ISSUE TITLE
There are 3 tests not passing in Pharo 9

### ISSUE THREAD

**Issue by oliveiraallex** [pharo-ide/TostSerializer#5]
There are 3 tests not passing in Pharo 9:

#testBlockClosureWithContex
#testBlockClosureWithoutContext
#testCompiledMethod

How can I fix them?

**Comment by dionisiydk** [comment]
It is related to FullBlockClosure and systa bytecode which was enabled
recently.

How to fix?


As anything else :).
Try to debug and find a solution. It is not really a fix by some meaning
but an implementation of serialization of new objects: methods and blocks
have new structure now

чт, 9 июл. 2020 г. в 14:57, oliveiraallex <notifications@github.com>:

**Comment by dionisiydk** [comment]
I know @pavel-krivanek start looking into it. Any news?

**Comment by dionisiydk** [comment]
Block closure tests are still failing:
#testBlockClosureWithContex 
#testBlockClosureWithoutContext

**Comment by dionisiydk** [comment]
I did a fix and will publish soon.
It actually allows me to find a critical bug in materialization logic of "well known objects" (like globals).

**Comment by dionisiydk** [comment]
fixed in v2.0.0.
It requires Seamless update (upcoming)
